sudo: required
dist: trusty
language: perl

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libdb-dev libxml2-dev libxslt1-dev texlive-latex-base

install:
 - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

script:
 - export PATH=~/perl5/bin:$PATH
 - cpanm https://github.com/KWARC/LaTeXML.git --notest
 - cpanm . -v --notest
 - cpanm . -v 